apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transactor
  name: transactor
  annotations:
    skupper.io/proxy: "http"  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactor
  template:
    metadata:
      labels:
        app: transactor
    spec:
      containers:
      - name: transactor
        image: docker.io/burrsutter/transaction:1.0.0
        imagePullPolicy: Always
        env:
          - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
            value: update
          - name: QUARKUS_DATASOURCE_JDBC_URL
            value: jdbc:postgresql://oltp-rdbms:5432/transactions
          - name: QUARKUS_DATASOURCE_USERNAME
            value: myuser
          - name: QUARKUS_DATASOURCE_PASSWORD
            value: mypassword
        resources:
          requests: 
            memory: "500Mi" 
            cpu: "1000m" 
          limits:
            memory: "500Mi"
            cpu: "1000m" 
        ports:
        - containerPort: 8080
          name: "http"     